### ISSUE TITLE
explanation

### ISSUE THREAD

**Issue by Smealm** [DocJr90/PlayniteAutomaticDriveDetection#1]
how do you use this? what exactly does it do?

**Comment by DocJr90** [comment]
First, it is important to point out that this plugin was developed for my specific use-case and simply published/shared in case it proves helpful to others, versus being purposefully developed for others.

As to your actual question, it might help to explain the problem it was created to solve: when installing games to a removable drive (or even an internal one such as when moving drives around, migrating to a new system, etc.), the letter assigned to the drive can easily change (at least on Windows) thus rendering games inaccessible through the launcher (or worse, the launcher could replace invalid paths with something unintuitive, like sometimes happens with UNC paths in Outlook, though I don't remember the documented functionality of Playnite/other plugins in regards to same).

Normally, fixing the drive letter/path issue would require editing each path individually or at least invoking some other already-available plugin manually. Accordingly, I wanted to automate the process: enter this plugin. The primary obstacle was to find some way to track drives as they are connected and disconnected - such as via serial number. However, this would require retrieving serial numbers via other utilities, physical access to drives, deeper knowledge of PC's, or simply more cumbersome steps. In contrast, one of the easiest ways to track drives - particularly of those accessible via native libraries while simultaneously allowing the user easy access to view and/or modify the identifier - is via volume/drive labels assigned to said drives.

Thus, this plugin:
"[...] automatically detects drive letter [...]"
"[...] based on specified volume label [...]"
"[...] and replaces drive letters [...]"
"[...] on game installation paths [...]"
"[...] accordingly."

**Comment by DocJr90** [comment]
I forgot to add instructions: simply change the drive/volume label of your game drive via Windows, and then enter that label in the plugin settings. Unfortunately, I can't be more specific at the moment as I am travelling.
